import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Snapshot } from '../system1/engine/buildSnapshot'
import { ingestSnapshot } from '../system2/engine/ingestSnapshot'
import type { OrgRecord } from '../system2/data/types'
import SNAPSHOT_SEED from '../system2/data/snapshot.seed.json'

/**
 * System 2's shared store. S2-M0's demoValue placeholder is gone — this is
 * the real foundation S2-M2 onward build on. Never reads snapshotStore
 * reactively, so a later change to System 1's data (or even a fresh Export)
 * has zero effect here until Import is clicked again.
 *
 * Seeded 27 Sept 2026. It used to start empty, so every System 2 screen
 * opened on "No snapshot imported yet" and nothing was reviewable until
 * someone manually ran an export and an import. It now starts from a
 * committed snapshot — generated by running the REAL buildSnapshot() over
 * the seed population with every record Approved (see
 * scripts/generate-snapshot-seed.ts), so the starting state is exactly what
 * a genuine export of the seed population produces, not a separately
 * invented dataset.
 *
 * The import/export path is untouched: importSnapshot() still does a full
 * replace, and re-importing after a real export overwrites the seed. Only
 * the starting state changed. Reset restores this same pre-imported state
 * rather than an empty one, so the demo is never one click from a blocked
 * screen.
 */

/** The seed, ingested once at module load — ingestSnapshot is pure and
    deterministic per person id, so this is the same OrgRecord[] every time. */
function seedRecords(): OrgRecord[] {
  return ingestSnapshot(SNAPSHOT_SEED as Snapshot)
}

interface System2State {
  records: OrgRecord[]
  importedAt: string | null
  /** Full replace, not a merge — re-importing overwrites the prior set entirely. Trivially satisfies "no drops, no duplicates": a straight map in ingestSnapshot(), then a full swap here. */
  importSnapshot: (snapshot: Snapshot) => void
  resetToSeed: () => void
}

export const useSystem2Store = create<System2State>()(
  persist(
    (set) => ({
      records: seedRecords(),
      importedAt: SNAPSHOT_SEED.exportedAt,
      importSnapshot: (snapshot) =>
        set({ records: ingestSnapshot(snapshot), importedAt: new Date().toISOString() }),
      resetToSeed: () => set({ records: seedRecords(), importedAt: SNAPSHOT_SEED.exportedAt }),
    }),
    {
      name: 'des-system2',
      /*
       * Bumped when the store gained its seed. Without this, anyone who had
       * already opened the app carries a persisted `records: []` in
       * localStorage, and rehydration would put that empty array straight
       * back over the seed — the screen would still open blocked and the
       * change would look like it had not worked at all.
       *
       * Any pre-v1 persisted state is discarded in favour of the seed. A
       * genuine import done after upgrading persists as v1 and survives
       * normally.
       */
      version: 1,
      migrate: () => ({ records: seedRecords(), importedAt: SNAPSHOT_SEED.exportedAt }),
    },
  ),
)
