import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Snapshot } from '../system1/engine/buildSnapshot'
import { ingestSnapshot } from '../system2/engine/ingestSnapshot'
import type { OrgRecord } from '../system2/data/types'
import SNAPSHOT_SEED from '../system2/data/snapshot.seed.json'

/**
 * System 2's shared store. S2-M0's demoValue placeholder is gone — this is
 * the real foundation S2-M2 onward build on. Never reads snapshotStore
 * reactively, so a later change to System 1's data (or even a fresh Export)
 * has zero effect here until Import is clicked again.
 *
 * Seeded 27 Sept 2026. It used to start empty, so every System 2 screen
 * opened on "No snapshot imported yet" and nothing was reviewable until
 * someone manually ran an export and an import. It now starts from a
 * committed snapshot — generated by running the REAL buildSnapshot() over
 * the seed population with every record Approved (see
 * scripts/generate-snapshot-seed.ts), so the starting state is exactly what
 * a genuine export of the seed population produces, not a separately
 * invented dataset.
 *
 * The import/export path is untouched: importSnapshot() still does a full
 * replace, and re-importing after a real export overwrites the seed. Only
 * the starting state changed. Reset restores this same pre-imported state
 * rather than an empty one, so the demo is never one click from a blocked
 * screen.
 */

/** The seed, ingested once at module load — ingestSnapshot is pure and
    deterministic per person id, so this is the same OrgRecord[] every time. */
function seedRecords(): OrgRecord[] {
  return ingestSnapshot(SNAPSHOT_SEED as Snapshot)
}

interface System2State {
  records: OrgRecord[]
  importedAt: string | null
  /**
   * Merge by person id: records in the snapshot are updated or added, records
   * already held and absent from the snapshot are kept.
   *
   * This was a full replace until 29 Sept 2026, which was right while System 2
   * started empty — the snapshot was the only data there had ever been. Once
   * the store gained a seeded 60-record baseline, replace became actively
   * wrong: the demo journey approves a handful of records, and importing them
   * erased the other 56. Executive Summary fell from £15.7m across three
   * divisions to £1.3m across one, so the happy path gutted the screen it
   * exists to show.
   *
   * An approval should move the organisation's position, not redefine the
   * organisation. S2-M1's signal still holds — a snapshot of N records still
   * produces exactly N updated-or-added records, no drops and no duplicates,
   * because the merge is keyed on id.
   */
  importSnapshot: (snapshot: Snapshot) => void
  resetToSeed: () => void
}

export const useSystem2Store = create<System2State>()(
  persist(
    (set) => ({
      records: seedRecords(),
      importedAt: SNAPSHOT_SEED.exportedAt,
      importSnapshot: (snapshot) =>
        set((state) => {
          const incoming = ingestSnapshot(snapshot)
          const byId = new Map(state.records.map((record) => [record.id, record]))
          for (const record of incoming) byId.set(record.id, record)
          return { records: [...byId.values()], importedAt: new Date().toISOString() }
        }),
      resetToSeed: () => set({ records: seedRecords(), importedAt: SNAPSHOT_SEED.exportedAt }),
    }),
    {
      name: 'des-system2',
      /*
       * Bumped when the store gained its seed. Without this, anyone who had
       * already opened the app carries a persisted `records: []` in
       * localStorage, and rehydration would put that empty array straight
       * back over the seed — the screen would still open blocked and the
       * change would look like it had not worked at all.
       *
       * Any pre-v1 persisted state is discarded in favour of the seed. A
       * genuine import done after upgrading persists as v1 and survives
       * normally.
       */
      version: 1,
      migrate: () => ({ records: seedRecords(), importedAt: SNAPSHOT_SEED.exportedAt }),
    },
  ),
)
